/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.GenerateLogs;
import Business.Organization.OrganizationDirectory;
import Business.Organization.WelfareOrganization;
import Business.Role.Role;
import Business.Role.Role.RoleType;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientApprovalWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Gunjan
 */
public class AssignPhysicianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignPhysicianJPanel
     */
    JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory;
    WelfareOrganization welfareOrganization;
    EcoSystem system;
    Enterprise enterprise;
    UserAccount account;
    PatientApprovalWorkRequest patientApprovalWorkRequest;
    private GenerateLogs logs;

    AssignPhysicianJPanel(JPanel userProcessContainer, UserAccount account, OrganizationDirectory organizationDirectory, WelfareOrganization welfareOrganization, Enterprise enterprise, EcoSystem system, PatientApprovalWorkRequest patientReq, GenerateLogs logs) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        this.enterprise = enterprise;
        this.welfareOrganization = (WelfareOrganization) welfareOrganization;
        this.system = system;
        this.account = account;
        this.patientApprovalWorkRequest = patientReq;
        this.logs = logs;
        populatePhysicianComboBox();
        txtPatientNameField.setText(patientReq.getPatientName());
    }

    public void populatePhysicianComboBox() {
        for (UserAccount a : welfareOrganization.getUserAccountDirectory().getUserAccountList()) {
            if (a.getRole().toString().equals("Business.Role.PhysicianRole")) {
                txtPhysicianComboBox.addItem(a.getEmployee().getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhysicianComboBox = new javax.swing.JComboBox<>();
        heading = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        lblPatientName = new javax.swing.JLabel();
        txtPatientNameField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 251, 251));

        txtPhysicianComboBox.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        heading.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Assign Physician");

        btnAssign.setBackground(new java.awt.Color(251, 251, 251));
        btnAssign.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblPatientName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPatientName.setText("Patient : ");

        txtPatientNameField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtPatientNameField.setEnabled(false);
        txtPatientNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameFieldActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(251, 251, 251));
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientNameField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPhysicianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnAssign)))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(27, 27, 27)
                .addComponent(heading)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhysicianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewPatientListJPanel panel = (ViewPatientListJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        String physician = txtPhysicianComboBox.getSelectedItem().toString();
        patientApprovalWorkRequest.setAssignedPhysician(physician);
        JOptionPane.showMessageDialog(null, "Physician " + physician + " assigned to Patient "+ txtPatientNameField.getText());
        try {
            logs.generateLogs(AssignPhysicianJPanel.class.getName(), physician +" assigned to" +patientApprovalWorkRequest.getPatientName());
        } catch (IOException ex) {
            Logger.getLogger(AssignPhysicianJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void txtPatientNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField txtPatientNameField;
    private javax.swing.JComboBox<String> txtPhysicianComboBox;
    // End of variables declaration//GEN-END:variables
}
