/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.GenerateLogs;
import Business.Organization.WelfareOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mayur
 */
public class VolunteerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private WelfareOrganization welfareOrganization;
    private EcoSystem system;
    private UserAccount account;
    private GenerateLogs logs;

    /**
     * Creates new form VolunteerWorkAreaJPanel
     */
    public VolunteerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, WelfareOrganization welfareOrganization, Enterprise enterprise, EcoSystem system, GenerateLogs logs) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.welfareOrganization = (WelfareOrganization) welfareOrganization;
        this.system = system;
        this.account = account;
        this.logs = logs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePatientProfile = new javax.swing.JButton();
        btnViewPatientList = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 251, 251));

        btnCreatePatientProfile.setBackground(new java.awt.Color(251, 251, 251));
        btnCreatePatientProfile.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCreatePatientProfile.setText("Create Patient Profile");
        btnCreatePatientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientProfileActionPerformed(evt);
            }
        });

        btnViewPatientList.setBackground(new java.awt.Color(251, 251, 251));
        btnViewPatientList.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnViewPatientList.setText("View Patient List");
        btnViewPatientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreatePatientProfile)
                    .addComponent(btnViewPatientList, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btnCreatePatientProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnViewPatientList, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePatientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientProfileActionPerformed
        // TODO add your handling code here:
        CreatePatientProfileJPanel createPatientProfileJPanel = new CreatePatientProfileJPanel(userProcessContainer, account, enterprise.getOrganizationDirectory(), welfareOrganization, enterprise, system, logs);
        userProcessContainer.add("createPatientProfileJPanel", createPatientProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnCreatePatientProfileActionPerformed

    private void btnViewPatientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientListActionPerformed
        // TODO add your handling code here:
        ViewPatientListJPanel viewPatientListJPanel = new ViewPatientListJPanel(userProcessContainer, account, enterprise.getOrganizationDirectory(), welfareOrganization, enterprise, system, logs);
        userProcessContainer.add("viewPatientListJPanel", viewPatientListJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPatientListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePatientProfile;
    private javax.swing.JButton btnViewPatientList;
    // End of variables declaration//GEN-END:variables
}
