/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DHSSRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.GenerateLogs;
import Business.Organization.DHSSOrganization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.WelfareOrganization;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.VolunteerRole.ViewPatientListJPanel;

/**
 *
 * @author Gunjan
 */
public class DHSSAdminWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    DHSSOrganization dhssOrganization;
    EcoSystem system;
    UserAccount account;
    private GenerateLogs logs;
    /**
     * Creates new form DHSSAdminWorkAreaJPanel
     */
    public DHSSAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DHSSOrganization dhssOrganization, Enterprise enterprise,  EcoSystem system, GenerateLogs logs) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.enterprise = enterprise;
       this.dhssOrganization = (DHSSOrganization)dhssOrganization;
       this.system = system;
       this.account = account;
       this.logs = logs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewPatientRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 251, 251));

        btnViewPatientRequest.setBackground(new java.awt.Color(251, 251, 251));
        btnViewPatientRequest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnViewPatientRequest.setText("View Patient Requests");
        btnViewPatientRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(btnViewPatientRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnViewPatientRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPatientRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientRequestActionPerformed
        // TODO add your handling code here:
        ViewPatientRequestJPanel viewPatientRequesJPanel = new ViewPatientRequestJPanel(userProcessContainer, account, enterprise.getOrganizationDirectory(), dhssOrganization, enterprise, system, logs);
        userProcessContainer.add("viewPatientRequesJPanel", viewPatientRequesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPatientRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPatientRequest;
    // End of variables declaration//GEN-END:variables
}
