/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PathologistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientLabTestWorkRequest;
import Business.WorkQueue.SendLabResultWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rohit
 */
public class ViewPatientMedicalRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientMedicalRecordJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private OrganizationDirectory organizationDirectory;
    private LabOrganization labOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    private PatientLabTestWorkRequest patientReq;
    String imageDir;
    File imageName;

    ViewPatientMedicalRecordJPanel(JPanel userProcessContainer, UserAccount account, OrganizationDirectory organizationDirectory, LabOrganization labOrganization, Enterprise enterprise, EcoSystem system, PatientLabTestWorkRequest patientReq) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organizationDirectory = organizationDirectory;
        this.labOrganization = labOrganization;
        this.enterprise = enterprise;
        this.system = system;
        this.patientReq = patientReq;
        populateMedicalRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateMedicalRecords() {
        lblName.setText(patientReq.getPatientName());
        txtRespiratoryRate.setText(String.valueOf(patientReq.getRespiratoryRate()));
        txtHeartRate.setText(String.valueOf(patientReq.getHeartRate()));
        txtBloodPressure.setText(String.valueOf(patientReq.getSystolicBloodPressure()));
        txtBodyTemperature.setText(String.valueOf(patientReq.getBodyTemperature()));
        txtHeight.setText(String.valueOf(patientReq.getHeight()));
        txtWeight.setText(String.valueOf(patientReq.getWeightInPounds()));
        txtAge.setText(String.valueOf(patientReq.getAge()));
        txtPhysicianComment.setText(String.valueOf(patientReq.getPhysicianComments()));
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount account : org.getUserAccountDirectory().getUserAccountList()) {
                if (account.getRole().toString().equals("Business.Role.SpecialistDoctorRole")) {
                    txtDoctorComboBox.addItem(account.getEmployee().getName());
                }
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblHealthCondition = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPhysicianComment = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        txtImgPath = new javax.swing.JTextField();
        btnSendReport = new javax.swing.JButton();
        txtBodyTemperature = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        lblAssignDoc = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblRespiratoryRate = new javax.swing.JLabel();
        lblBodyTemperature = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPatientName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPathologistComments = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPathologistComments = new javax.swing.JTextArea();
        txtDoctorComboBox = new javax.swing.JComboBox<>();
        lblBloodPressure1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 251, 251));

        heading.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Patient Medical Record");

        lblHeight.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblHeight.setText("Height");

        txtHeight.setBackground(new java.awt.Color(251, 251, 251));
        txtHeight.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtHeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHeight.setEnabled(false);

        lblWeight.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblWeight.setText("Weight");

        txtWeight.setBackground(new java.awt.Color(251, 251, 251));
        txtWeight.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtWeight.setEnabled(false);
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblAge.setText("Age");

        txtAge.setBackground(new java.awt.Color(251, 251, 251));
        txtAge.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAge.setEnabled(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblHealthCondition.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblHealthCondition.setText("Physician Comments");

        txtPhysicianComment.setColumns(20);
        txtPhysicianComment.setRows(5);
        txtPhysicianComment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPhysicianComment.setEnabled(false);
        jScrollPane1.setViewportView(txtPhysicianComment);

        btnBack.setBackground(new java.awt.Color(251, 251, 251));
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpload.setText("Attach Lab Report");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        txtImgPath.setBackground(new java.awt.Color(251, 251, 251));
        txtImgPath.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtImgPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtImgPath.setEnabled(false);
        txtImgPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImgPathActionPerformed(evt);
            }
        });

        btnSendReport.setBackground(new java.awt.Color(251, 251, 251));
        btnSendReport.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSendReport.setText("Send Report");
        btnSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReportActionPerformed(evt);
            }
        });

        txtBodyTemperature.setBackground(new java.awt.Color(251, 251, 251));
        txtBodyTemperature.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtBodyTemperature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtBloodPressure.setBackground(new java.awt.Color(251, 251, 251));
        txtBloodPressure.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtBloodPressure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtHeartRate.setBackground(new java.awt.Color(251, 251, 251));
        txtHeartRate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtHeartRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtRespiratoryRate.setBackground(new java.awt.Color(251, 251, 251));
        txtRespiratoryRate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtRespiratoryRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRespiratoryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespiratoryRateActionPerformed(evt);
            }
        });

        lblAssignDoc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblAssignDoc.setText("Assign Doctor");

        lblHeartRate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblHeartRate.setText("Heart Rate");

        lblRespiratoryRate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRespiratoryRate.setText("Respiratory Rate");

        lblBodyTemperature.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblBodyTemperature.setText("Body Temperature");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblPatientName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPatientName.setText("Patient Name:");

        lblName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblName.setText("<patient Name>");

        lblPathologistComments.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPathologistComments.setText("Pathologist Comments");

        txtPathologistComments.setColumns(20);
        txtPathologistComments.setRows(5);
        txtPathologistComments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtPathologistComments);

        lblBloodPressure1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblBloodPressure1.setText("Blood Pressure");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lblBodyTemperature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblHeartRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBloodPressure1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(24, 24, 24)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHealthCondition)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSendReport, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAssignDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtImgPath)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblPathologistComments)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(89, 89, 89)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPatientName)
                                    .addComponent(lblName))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRespiratoryRate)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHeartRate)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBodyTemperature)
                                            .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblHeight)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblWeight)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAge))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBloodPressure1))
                                        .addGap(53, 53, 53)
                                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPathologistComments, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAssignDoc))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpload)
                                    .addComponent(txtImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHealthCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PathologistWorkAreaJPanel panel = (PathologistWorkAreaJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser uploadImg = new JFileChooser();
        uploadImg.showOpenDialog(null);
        imageName = uploadImg.getSelectedFile();
        imageDir = imageName.getAbsolutePath();
        txtImgPath.setText(imageDir);

    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtImgPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImgPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgPathActionPerformed

    private void btnSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReportActionPerformed
        // TODO add your handling code here:
        if(patientReq.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null, "Lab report already to Specialist for "+patientReq.getPatientName());
        }else{
        SendLabResultWorkRequest sendLabRequestWorkRequest = new SendLabResultWorkRequest();
        sendLabRequestWorkRequest.setPatientId(patientReq.getPatientId());
        sendLabRequestWorkRequest.setPatientName(patientReq.getPatientName());
        sendLabRequestWorkRequest.setFilePath(imageDir);
        sendLabRequestWorkRequest.setPathologistComments(txtPathologistComments.getText());
        sendLabRequestWorkRequest.setSender(account);
        sendLabRequestWorkRequest.setRequestDate(new Date());
        sendLabRequestWorkRequest.setAssignedDoctor(txtDoctorComboBox.getSelectedItem().toString());
        sendLabRequestWorkRequest.setAge(Integer.parseInt(txtAge.getText()));
        Organization docOrg = null;
        Organization labOrg = null;

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof LabOrganization) {
                labOrg = organization;
                break;
            }
        }
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DoctorOrganization) {
                docOrg = organization;
                break;
            }
        }
        if (labOrg != null && docOrg != null) {
            labOrg.getWorkQueue().getWorkRequestList().add(sendLabRequestWorkRequest);
            docOrg.getWorkQueue().getWorkRequestList().add(sendLabRequestWorkRequest);
        }
        JOptionPane.showMessageDialog(null, "Lab report sent to Specialist");
        patientReq.setStatus("Completed");
        sendLabRequestWorkRequest.setStatus("Pending");
        }
    }//GEN-LAST:event_btnSendReportActionPerformed

    private void txtRespiratoryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespiratoryRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendReport;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAssignDoc;
    private javax.swing.JLabel lblBloodPressure1;
    private javax.swing.JLabel lblBodyTemperature;
    private javax.swing.JLabel lblHealthCondition;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPathologistComments;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemperature;
    private javax.swing.JComboBox<String> txtDoctorComboBox;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtImgPath;
    private javax.swing.JTextArea txtPathologistComments;
    private javax.swing.JTextArea txtPhysicianComment;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
